# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VarensTradeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VarensTradeApp

  pod 'PTCardTabBar'
  #pod 'Charts'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftCharts', '~> 0.6.5'
  #pod 'SwiftChart'

end
